CAR_BRANDS= (
    ('toyota', 'Toyota'),
    ('nissan', 'Nissan'),
    ('mazda', 'Mazda'),
    ('mitsubishi', 'Mitsubishi'),
    ('honda', 'Honda'),
    ('subaru', 'Subaru'),
    ('audi', 'Audi'),
    ('bmw', 'BMW'),
    ('volkswagen', 'Volkswagen'),
    ('volvo', 'Volvo'),
    ('lexus', 'Lexus'),
    ('infiniti', 'Infiniti'),
    ('kia', 'Kia'),
    ('mercedes-benz', 'Mercedes-Benz'),
    ('jaguar', 'Jaguar'),
    ('porsche', 'Porsche'),
    ('lamborghini', 'Lamborghini'),
    ('bugatti', 'Bugatti'),
    ('rolls-royce', 'Rolls-Royce'),
    ('aston-martin', 'Aston Martin'),
    ('ferrari', 'Ferrari'),
    ('mclaren', 'McLaren'),
    ('cadillac', 'Cadillac'),
    ('lincoln', 'Lincoln'),
    ('chrysler', 'Chrysler'),
    ('dodge', 'Dodge'),
    ('jeep', 'Jeep'),)
TRANSMISSION_OPTIONS = (
    ('manual', 'Manual'),
    ('automatic', 'Automatic'),
    ('semi-automatic', 'Semi-Automatic'),
    ('cvt', 'CVT'),
    ('dual-clutch', 'Dual-Clutch'),
)