# Generated by Django 5.2.4 on 2025-07-27 21:29

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic'), ('cvt', 'CVT'), ('dual-clutch', 'Dual-Clutch')], default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('honda', 'Honda'), ('subaru', 'Subaru'), ('audi', 'Audi'), ('bmw', 'BMW'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo'), ('lexus', 'Lexus'), ('infiniti', 'Infiniti'), ('kia', 'Kia'), ('mercedes-benz', 'Mercedes-Benz'), ('jaguar', 'Jaguar'), ('porsche', 'Porsche'), ('lamborghini', 'Lamborghini'), ('bugatti', 'Bugatti'), ('rolls-royce', 'Rolls-Royce'), ('aston-martin', 'Aston Martin'), ('ferrari', 'Ferrari'), ('mclaren', 'McLaren'), ('cadillac', 'Cadillac'), ('lincoln', 'Lincoln'), ('chrysler', 'Chrysler'), ('dodge', 'Dodge'), ('jeep', 'Jeep')], default='toyota', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.user_listings_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(default='', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
